import {inter} from '@/app/ui/fonts';
import "./globals.css";
import Providers from "@/app/providers";
import ThemeButton from "@/app/components/ThemeButton";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Providers>
            <header>
                <ThemeButton/>
            </header>
            {children}
        </Providers>
        </body>
        </html>
    );
}
